export const ORDER_STATUS = {
  DRAFT: 'DRAFT',
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  PARTIAL_ISSUED: 'PARTIAL_ISSUED',
  ISSUED: 'ISSUED',
  RECEIVED: 'RECEIVED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export type OrderStatus = (typeof ORDER_STATUS)[keyof typeof ORDER_STATUS];
export const ORDER_STATUSES = Object.values(ORDER_STATUS) as OrderStatus[];

export const STOCK_TRANSACTION_TYPE_CODE = {
  ISSUE: 'ISSUE',
  RECEIVE: 'RECEIVE',
  ADJUSTMENT_IN: 'ADJUSTMENT_IN',
  ADJUSTMENT_OUT: 'ADJUSTMENT_OUT',
  TRANSFER_IN: 'TRANSFER_IN',
  TRANSFER_OUT: 'TRANSFER_OUT',
  IMPORT: 'IMPORT',
  EXPORT: 'EXPORT',
  REVERSAL_IN: 'REVERSAL_IN',
  REVERSAL_OUT: 'REVERSAL_OUT',
} as const;

export type StockTransactionType =
  (typeof STOCK_TRANSACTION_TYPE_CODE)[keyof typeof STOCK_TRANSACTION_TYPE_CODE];
export const STOCK_TRANSACTION_TYPES =
  Object.values(STOCK_TRANSACTION_TYPE_CODE) as StockTransactionType[];

export const ORDER_REVISION_ACTION = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
  ISSUE: 'ISSUE',
  CANCEL: 'CANCEL',
  REVERT_STATUS: 'REVERT_STATUS',
  STOCK_REVERSAL: 'STOCK_REVERSAL',
} as const;

export type OrderRevisionActionCode =
  (typeof ORDER_REVISION_ACTION)[keyof typeof ORDER_REVISION_ACTION];
