export const MILKRUN_TRIP_TYPE_CODE = {
  RECEIVE_RACK: 'RECEIVE_RACK',
  RETURN_RACK: 'RETURN_RACK',
} as const;

export const MILKRUN_TRIP_STATUS_CODE = {
  REGISTERED: 'REGISTERED',
  STARTED: 'STARTED',
  ARRIVED: 'ARRIVED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export const MILKRUN_STOCK_TRANSACTION_TYPE_CODE = {
  IN: 'IN',
  OUT: 'OUT',
  ADJUSTMENT_IN: 'ADJUSTMENT_IN',
  ADJUSTMENT_OUT: 'ADJUSTMENT_OUT',
  REVERSAL_IN: 'REVERSAL_IN',
  REVERSAL_OUT: 'REVERSAL_OUT',
} as const;

export const MILKRUN_STOCK_EFFECT = {
  INCREASE: 'INCREASE',
  DECREASE: 'DECREASE',
  NEUTRAL: 'NEUTRAL',
} as const;
